CREATE DATABASE PENTAX_ACADEMY;
USE PENTAX_ACADEMY;

CREATE TABLE STUDENT(
   StudentId INTEGER NOT NULL AUTO_INCREMENT,
   FirstName CHAR(45) NOT NULL,
   LastName  CHAR(45) NOT NULL,
   Department CHAR(45) NOT NULL,
   Gender 	  CHAR(10) NOT NULL,
   TeacherId  CHAR(6)  NOT NULL,
   ClassId    CHAR(6)  NOT NULL,
   CONSTRAINT STUDENT_pk PRIMARY KEY(StudentId),
   CONSTRAINT TEACHER_fk FOREIGN KEY(TeacherId)
						 REFERENCES TEACHER(TeacherId),
   CONSTRAINT CLASS_fk   FOREIGN KEY(ClassId)
						 REFERENCES CLASS(ClassId)
);
CREATE TABLE TEACHER(
   TeacherId  CHAR(6)  NOT NULL,
   FirstName  CHAR(45) NOT NULL,
   LastName   CHAR(45) NOT NULL,
   Department CHAR(40) NOT NULL,
   Gender 	  CHAR(10) NOT NULL,
   CONSTRAINT  TEACHER_ID PRIMARY KEY(TeacherId)
);
CREATE TABLE CLASS(
   ClassId    CHAR(6)  NOT NULL,
   ClassName  CHAR(45) NOT NULL,
   Term       CHAR(45) NOT NULL,
   CONSTRAINT  CLASS_ID PRIMARY KEY(ClassId)
);
CREATE TABLE GRADE(
   StudentId   INTEGER    NOT NULL AUTO_INCREMENT,
   ClassId     CHAR(6)    NOT NULL,
   Scores      INTEGER    NOT NULL,
   SubjectId   CHAR(6)    NOT NULL,
   CONSTRAINT  GRADE_pk   PRIMARY KEY(StudentId),
   CONSTRAINT  fk_CLASS_GRADE   FOREIGN KEY(ClassId)
						        REFERENCES CLASS(ClassId),
   CONSTRAINT  SUBJECT_fk       FOREIGN KEY(SubjectId)
						        REFERENCES SUBJECT(SubjectId)
);
CREATE TABLE SUBJECT(
   SubjectId   CHAR(6)    NOT NULL,
   SubjectName CHAR(45)   NOT NULL,
   Scores      INTEGER    NOT NULL,
   Grades      VARCHAR(3) NOT NULL,
   StudentId   INTEGER    NOT NULL AUTO_INCREMENT,
   ClassId     CHAR(6)    NOT NULL,
   TeacherId   CHAR(6)    NOT NULL,
   CONSTRAINT  SUBJECT_pk   PRIMARY KEY(SubjectId),
   CONSTRAINT  STUDENT_fk   FOREIGN KEY(StudentId)
						  REFERENCES STUDENT(StudentId)
);

USE PENTAX_ACADEMY;
DROP TABLE account;

